name: Legatum 2.0 2023
markdown: redcarpet
highlighter: rouge
sass:
    style: expanded
    deploy_style: compressed
    compile_in_place: true
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
exclude_from_localizations: ["javascript", "images", "css"]
